import type { FeatureCategory, FeatureOption, PortraitLibrary } from "./types";

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const opt = (label: string, value: string): Omit<FeatureOption, "id"> & { _label: string } => ({
  _label: label,
  label,
  value,
});

// Deterministic option ID built from the category key + option label, so the
// same option always has the same ID across reloads, builds, and users.
const finalizeCategory = (
  cat: Omit<FeatureCategory, "options"> & {
    options: (Omit<FeatureOption, "id"> & { _label: string })[];
  }
): FeatureCategory => ({
  ...cat,
  options: cat.options.map((o) => ({
    id: `opt-${slug(cat.key)}-${slug(o._label)}`,
    label: o.label,
    value: o.value,
  })),
});

export const DEFAULT_BASE_TEMPLATE =
  "a [AGE] [ETHNICITY] [GENDER], [FACE_SHAPE] face, [JAWLINE] jawline, [CHEEKBONES] cheekbones, [EYE_SHAPE] [EYE_COLOR] eyes, [EYE_FEATURE], [EYEBROWS] eyebrows, [NOSE] nose, [LIPS], [FACIAL_HAIR], [HAIR_COLOR] [HAIR_STYLE], [EXPRESSION] expression, facing the camera with a neutral pose. sports portrait shot. wearing plain black sports jersey. solid white background. [LIGHTING]. [ART_STYLE] --ar 3:4 --niji 7";

const RAW_CATEGORIES = [
    {
      id: "cat-ethnicity",
      key: "ETHNICITY",
      label: "Ethnicity",
      slot: "[ETHNICITY]",
      required: true,
      allowNone: false,
      options: [
        opt("East Asian", "East Asian features with light skin"),
        opt("Southeast Asian", "Southeast Asian features with warm tan skin"),
        opt("South Asian", "South Asian features with brown skin"),
        opt("Central Asian", "Central Asian features with light olive skin"),
        opt("Middle Eastern", "Middle Eastern features with olive skin"),
        opt("North African", "North African features with bronze skin"),
        opt("West African", "West African features with deep brown skin"),
        opt("East African", "East African features with dark brown skin"),
        opt("Northern European", "Northern European features with very fair skin"),
        opt("Mediterranean", "Mediterranean features with warm olive skin"),
        opt("Eastern European", "Eastern European features with pale skin"),
        opt("Latin American", "Latin American features with tan skin"),
        opt("Polynesian", "Polynesian features with golden brown skin"),
        opt("Ambiguous", "racially ambiguous features with medium skin"),
      ],
    },
    {
      id: "cat-age",
      key: "AGE",
      label: "Age",
      slot: "[AGE]",
      required: true,
      allowNone: false,
      options: [
        opt("Teen (16-19)", "teenage 17-year-old"),
        opt("Early 20s", "young 22-year-old"),
        opt("Mid 20s", "25-year-old"),
        opt("Late 20s", "28-year-old"),
        opt("Early 30s", "32-year-old"),
        opt("Mid 30s", "35-year-old"),
        opt("40s", "42-year-old"),
      ],
    },
    {
      id: "cat-gender",
      key: "GENDER",
      label: "Gender",
      slot: "[GENDER]",
      required: true,
      allowNone: false,
      options: [opt("Male", "man")],
    },
    {
      id: "cat-face",
      key: "FACE_SHAPE",
      label: "Face Shape",
      slot: "[FACE_SHAPE]",
      required: false,
      allowNone: true,
      options: [
        opt("Oval", "oval"),
        opt("Round", "round"),
        opt("Square", "square"),
        opt("Heart", "heart-shaped"),
        opt("Diamond", "diamond-shaped"),
        opt("Oblong", "oblong"),
        opt("Triangle", "triangular"),
      ],
    },
    {
      id: "cat-jaw",
      key: "JAWLINE",
      label: "Jawline",
      slot: "[JAWLINE]",
      required: false,
      allowNone: true,
      options: [
        opt("Strong", "strong defined"),
        opt("Soft", "soft rounded"),
        opt("Sharp", "sharp angular"),
        opt("Wide", "wide square"),
        opt("Narrow", "narrow tapered"),
      ],
    },
    {
      id: "cat-cheekbones",
      key: "CHEEKBONES",
      label: "Cheekbones",
      slot: "[CHEEKBONES]",
      required: false,
      allowNone: true,
      options: [
        opt("High & Prominent", "high prominent"),
        opt("Soft & Flat", "soft flat"),
        opt("Wide", "wide"),
        opt("Hollow", "hollow sunken"),
      ],
    },
    {
      id: "cat-eye-shape",
      key: "EYE_SHAPE",
      label: "Eye Shape",
      slot: "[EYE_SHAPE]",
      required: false,
      allowNone: true,
      options: [
        opt("Almond", "almond-shaped"),
        opt("Round", "round"),
        opt("Monolid", "monolid"),
        opt("Hooded", "hooded"),
        opt("Upturned", "upturned"),
        opt("Downturned", "downturned"),
        opt("Deep set", "deep-set"),
        opt("Wide set", "wide-set"),
        opt("Close set", "close-set"),
      ],
    },
    {
      id: "cat-eye-color",
      key: "EYE_COLOR",
      label: "Eye Color",
      slot: "[EYE_COLOR]",
      required: false,
      allowNone: true,
      options: [
        opt("Black", "black"),
        opt("Dark Brown", "dark brown"),
        opt("Light Brown", "light brown"),
        opt("Amber", "amber"),
        opt("Hazel", "hazel"),
        opt("Green", "green"),
        opt("Blue", "blue"),
        opt("Gray", "gray"),
      ],
    },
    {
      id: "cat-eye-feature",
      key: "EYE_FEATURE",
      label: "Eye Feature",
      slot: "[EYE_FEATURE]",
      required: false,
      allowNone: true,
      options: [
        opt("Thick Lashes", "thick lashes"),
        opt("Monolid Crease", "subtle monolid crease"),
        opt("Heavy Brow", "heavy brow ridge"),
      ],
    },
    {
      id: "cat-eyebrows",
      key: "EYEBROWS",
      label: "Eyebrows",
      slot: "[EYEBROWS]",
      required: false,
      allowNone: true,
      options: [
        opt("Thick Straight", "thick straight"),
        opt("Thick Arched", "thick arched"),
        opt("Thin Arched", "thin arched"),
        opt("Bushy", "bushy"),
        opt("Flat Straight", "flat straight"),
        opt("Sparse", "sparse"),
        opt("Angled Sharp", "sharply angled"),
      ],
    },
    {
      id: "cat-nose",
      key: "NOSE",
      label: "Nose",
      slot: "[NOSE]",
      required: false,
      allowNone: true,
      options: [
        opt("Narrow Straight", "narrow straight"),
        opt("Wide Flat", "wide flat"),
        opt("Button", "small button"),
        opt("Aquiline", "aquiline hooked"),
        opt("Broad", "broad"),
        opt("Upturned", "upturned"),
        opt("Long Straight", "long straight"),
        opt("Bulbous Tip", "bulbous-tipped"),
      ],
    },
    {
      id: "cat-lips",
      key: "LIPS",
      label: "Mouth / Lips",
      slot: "[LIPS]",
      required: false,
      allowNone: true,
      options: [
        opt("Thin Lips", "thin lips"),
        opt("Full Lips", "full lips"),
        opt("Wide Mouth", "wide mouth"),
        opt("Small Mouth", "small mouth"),
        opt("Defined Cupid's Bow", "defined cupid's bow lips"),
        opt("Downturned Corners", "downturned mouth corners"),
        opt("Upturned Corners", "upturned mouth corners"),
      ],
    },
    {
      id: "cat-facial-hair",
      key: "FACIAL_HAIR",
      label: "Facial Hair",
      slot: "[FACIAL_HAIR]",
      required: false,
      allowNone: true,
      options: [
        opt("None", "clean shaven"),
        opt("Light Stubble", "light stubble"),
        opt("Short Beard", "short trimmed beard"),
        opt("Full Beard", "full beard"),
        opt("Goatee", "goatee"),
        opt("Mustache", "mustache"),
        opt("Thick Mustache", "thick mustache"),
      ],
    },
    {
      id: "cat-hair-style",
      key: "HAIR_STYLE",
      label: "Hair Style",
      slot: "[HAIR_STYLE]",
      required: true,
      allowNone: false,
      options: [
        opt("Buzz Cut", "buzz cut"),
        opt("Short Cropped", "short cropped"),
        opt("Crew Cut", "crew cut"),
        opt("Undercut", "undercut"),
        opt("Slicked Back", "slicked back"),
        opt("Tousled Medium", "tousled medium-length"),
        opt("Man Bun", "tied man bun"),
        opt("Curly Short", "short curly"),
        opt("Curly Medium", "medium curly"),
        opt("Afro", "afro"),
        opt("Locs Short", "short locs"),
        opt("Locs Long", "long locs"),
        opt("Cornrows", "cornrows"),
        opt("Wavy Swept", "wavy swept-back"),
        opt("Mohawk", "mohawk"),
      ],
    },
    {
      id: "cat-hair-color",
      key: "HAIR_COLOR",
      label: "Hair Color",
      slot: "[HAIR_COLOR]",
      required: true,
      allowNone: false,
      options: [
        opt("Black", "black"),
        opt("Dark Brown", "dark brown"),
        opt("Medium Brown", "medium brown"),
        opt("Light Brown", "light brown"),
        opt("Dirty Blonde", "dirty blonde"),
        opt("Platinum Blonde", "platinum blonde"),
        opt("Auburn", "auburn"),
        opt("Red", "red"),
        opt("Deep Red", "deep red"),
        opt("Gray", "gray"),
        opt("White", "white"),
        opt("Purple", "purple"),
        opt("Blue", "blue"),
        opt("Pink", "pink"),
        opt("Green", "green"),
        opt("Teal", "teal"),
        opt("Orange", "orange"),
        opt("Silver", "silver"),
        opt("Two-Tone", "two-tone split-dyed"),
      ],
    },
    {
      id: "cat-expression",
      key: "EXPRESSION",
      label: "Expression",
      slot: "[EXPRESSION]",
      required: false,
      allowNone: true,
      options: [
        opt("Neutral", "neutral"),
        opt("Confident", "confident"),
        opt("Slight Smile", "slight smile"),
        opt("Serious", "serious"),
        opt("Calm", "calm"),
        opt("Intense", "intense focused"),
      ],
    },
    {
      id: "cat-lighting",
      key: "LIGHTING",
      label: "Lighting",
      slot: "[LIGHTING]",
      required: false,
      allowNone: true,
      options: [
        opt("Soft Studio", "soft even studio lighting"),
        opt("Rim Light", "subtle rim lighting"),
        opt("Flat Front", "flat front lighting"),
        opt("Dramatic Side", "dramatic side lighting"),
      ],
    },
    {
      id: "cat-art-style",
      key: "ART_STYLE",
      label: "Art Style",
      slot: "[ART_STYLE]",
      required: true,
      allowNone: false,
      options: [
        opt("Anime", "anime art style."),
        opt("Semi-Realistic Anime", "semi-realistic anime illustration."),
        opt("Manga Ink", "clean manga ink illustration."),
      ],
    },
  ] as const;

export const DEFAULT_LIBRARY: PortraitLibrary = {
  version: 1,
  basePromptTemplate: DEFAULT_BASE_TEMPLATE,
  categories: RAW_CATEGORIES.map((c) =>
    finalizeCategory({
      id: c.id,
      key: c.key,
      label: c.label,
      slot: c.slot,
      required: c.required,
      allowNone: c.allowNone,
      options: [...c.options],
    })
  ),
};
